title: Michael Cypher
email: michael@cypher.codes
url: "https://cypher.codes"
baseurl: ""
linkedin_username: mikeecb

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from

include: [_lists]

highlighter: rouge

permalink: /writing/:title
redirects: yes
